### ISSUE TITLE
Hi, would you enlighten how to install zeppelin-ultimate-column-chart to Zeppelin version 0.7.3? Thank you.

### ISSUE THREAD

**Issue by ericchchiu** [ZEPL/zeppelin-ultimate-column-chart#2]
Hi, would you enlighten how to install zeppelin-ultimate-column-chart to Zeppelin version 0.7.3? Thank you. I have tried to do it for so many time but not successful.

**Comment by sravan-s** [comment]
I'm afraid we can only use `zeppelin-ultimate-column-chart` or any other `helium` charts with Zeppelin 0.8

**Comment by ericchchiu** [comment]
My problem is that the current version of Zeppelin is 0.7.3 and the snapshot version posted at git is now 0.9. I encountered the same problem as other people discussed on the web: when building the snapshot from source, it failed at "web application".

**Comment by ericchchiu** [comment]
Sorry, Sravan, forget to say thank you for your message. All the best.

**Comment by sravan-s** [comment]
Did you try building branch 0.8? https://github.com/apache/zeppelin/tree/branch-0.8
